name: Build and Push Docker image to Docker Hub

on:
  push:
    branches: ["main"]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    defaults:
      run:
        working-directory: "/Lap3/git_cicd"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Lap3/git_cicd/
          push: true
          tags: tienlong1106/git_cicd:latest
